FROM envoyproxy/envoy:v1.16-latest

# COPY ./entrypoint.sh /

# COPY ./envoy.yaml /etc/envoy/envoy.yml

# RUN chmod go+r /etc/envoy/envoy.yaml

# RUN chmod 500 /entrypoint.sh

# ENTRYPOINT ["/entrypoint.sh"]
