version: '3.7'

services:
  productdb:
    container_name: productdb
    environment:
      - SA_PASSWORD=admin!234
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "8033:1433"
    volumes:
      - mssql_volume:/var/opt/mssql

  portainer:
    container_name: portainer
    restart: always
    ports:
      - 8080:8000
      - 9090:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  mango.services.productapi:
    container_name: mango.services.productapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=productdb;Port=1433;Database=ProductDB;User Id=sa;Password=admin!234;"
    ports:
      - "8001:8001"
      - "9001:9001"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - productdb

