version: '3.7'

services:
  productdb:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    
  portainer:
    image: portainer/portainer-ce
  
  mango.services.productapi:
    image: ${DOCKER_REGISTRY-}mangoservices
    build:
      context: .
      dockerfile: Mango.Services.ProductAPI/Dockerfile


volumes:
  mssql_volume:
  portainer_data: