version: '3.7'

services:
  productdb:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    
  portainer:
    image: portainer/portainer-ce
  
  mango.services.productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Mango.Services.ProductAPI/Dockerfile


  mango.services.authapi:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Mango.Services.AuthAPI/Dockerfile

  envoy:
    image: ${DOCKER_REGISTRY-}envoy
    build:
      context: .
      dockerfile: ./Envoy/Dockerfile

volumes:
  mssql_volume:
  portainer_data:

