version: '3.7'

services:
  productdb:
    container_name: productdb
    environment:
      - SA_PASSWORD=admin!234
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "8033:1433"
    volumes:
      - mssql_volume:/var/opt/mssql

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  mango.services.productapi:
    container_name: mango.services.productapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=productdb,1433;Database=ProductDB;Trusted_Connection=false;MultipleActiveResultSets=true;User Id=sa;Password=admin!234;"
    ports:
      - "8001:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - productdb

  mango.services.authapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8002:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  envoy:
    container_name: envoy
    ports:
      - "9901:9901"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./Envoy/envoy.yml:/config/envoy.yml
    depends_on:
      - mango.services.productapi
      - mango.services.authapi
